change pipline code

diff --git a/.github/workflows/terraform_provider.yml b/.github/workflows/terraform_provider.yml
--- a/.github/workflows/terraform_provider.yml
+++ b/.github/workflows/terraform_provider.yml
@@ -153,12 +153,14 @@ jobs:
 
       - name: Generate docs and check for differences
         run: |
-          if git diff HEAD --exit-code --quiet -- .changes/unreleased; then
-            echo "You forgot to add a Changie log with 'changie new' command"
+          git diff HEAD --exit-code --quiet -- .changes/unreleased
+          if [ $? -eq 0 ]; then
+             echo "You forgot to add a Changie log with 'changie new' command"
             exit 1
-          elif [ $? -ne 0 ]; then
-            echo "Error occurred in 'git diff'"
-            exit $?
+          elif [ $? -eq 1 ]; then
+            echo "Changes found"
+            exit 0
           fi
-          exit 0
+          echo "Error occurred in `git diff`"
+          exit $?
 
